spring.application.name=salon-ecomm
spring.profiles.active=local
# Set active profile via env var SPRING_PROFILES_ACTIVE or -Dspring.profiles.active
# e.g. local (for local dev), docker (for container), dev/prod etc.
