spring.datasource.url=jdbc:postgresql://aws-1-ap-northeast-1.pooler.supabase.com:5432/postgres?user=postgres.coogfznfrbdkhhzowtkn&password=Supasupabase777
spring.datasource.username=postgres.coogfznfrbdkhhzowtkn
spring.datasource.password=Supasupabase777
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

spring.graphql.http.path=/graphql

server.port=8080

app.production=true

