spring.application.name=salon-ecomm
spring.profiles.active=local

spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.pool-name=SalonEcommPool
spring.graphql.graphiql.enabled=true
# Set active profile via env var SPRING_PROFILES_ACTIVE or -Dspring.profiles.active
# e.g. local (for local dev), docker (for container), dev/prod etc.

security.jwt.secret-key=${JWT_SECRET}
security.jwt.expiration-time=${JWT_EXPIRATION}
security.jwt.refresh-expiration-time=604800000

spring.data.redis.repositories.enabled=false
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.data.redis.RedisReactiveAutoConfiguration

spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=email,profile

#Mail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=bgwhiskey64@gmail.com
spring.mail.password=${APP_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.config.import=optional:file:.env[.properties]

# local
app.cors.allowed-origins=http://localhost:3000

cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api-key=${CLOUDINARY_API_KEY}
cloudinary.api-secret=${CLOUDINARY_API_SECRET}

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=25MB
