package com.verdant.salon_ecomm.models.enums.audit;

public enum AuditActionType {
    CREATED,
    BOOKED,
    RESTOCKED,
    FAVORITE,
    UPDATED,
    CANCELLED,
    DELETED,
    SECURITY,
    ADMINISTRATIVE,
    PAYMENT_INITIATED,
    PAYMENT_SUCCEEDED,
    PAYMENT_FAILED,
    PAYMENT_REFUNDED,
    UNFAVORITED,
    RESCHEDULED,
    APPROVED,
    REJECTED,
    COMPLETED,
    REVIEWED,
    IMAGE_UPDATED,
    STATUS_CHANGED,
    ASSIGNED,
    BULK_CANCELLED,
    BULK_DELETED
}